version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dependencies"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dependencies"
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
