name: "Codestyle check"

on:
  pull_request:
    paths:
      - "**.php"
      - "phpcs.xml"
      - ".github/workflows/phpcs.yml"
   

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install PHP_CodeSniffer
        run: |
          git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
          git clone -b master https://github.com/WordPress/WordPress-Coding-Standards.git wpcs
          cd phpcs 
          ./bin/phpcs --config-set installed_paths ../wpcs
      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: phpcs
          standard: phpcs.xml